# permissions for end users to edit dextokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dexchange
    app.kubernetes.io/managed-by: kustomize
  name: dextoken-editor-role
rules:
- apiGroups:
  - dexchange.miscord.win
  resources:
  - dextokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dexchange.miscord.win
  resources:
  - dextokens/status
  verbs:
  - get
