---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - dexchange.miscord.win
  resources:
  - dextokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dexchange.miscord.win
  resources:
  - dextokens/finalizers
  verbs:
  - update
- apiGroups:
  - dexchange.miscord.win
  resources:
  - dextokens/status
  verbs:
  - get
  - patch
  - update
